/*
 * Generated by JasperReports - 11/14/11 2:16 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class DetailPerusahaan_1321254983255_747094 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_ho_nomor = null;
    private JRFillField field_nama_perusahaan = null;
    private JRFillField field_imb_nomor = null;
    private JRFillField field_modal_kerja = null;
    private JRFillField field_kota = null;
    private JRFillField field_gudang_tanggal = null;
    private JRFillField field_dok_amdal = null;
    private JRFillField field_nilai_eksport = null;
    private JRFillField field_jenis_produksi = null;
    private JRFillField field_jml_tki_p = null;
    private JRFillField field_jml_tki_l = null;
    private JRFillField field_imb_tanggal = null;
    private JRFillField field_alamat_jalan = null;
    private JRFillField field_nama = null;
    private JRFillField field_tdp_nomor = null;
    private JRFillField field_telp = null;
    private JRFillField field_siup_nomor = null;
    private JRFillField field_ho_tanggal = null;
    private JRFillField field_produk = null;
    private JRFillField field_fax = null;
    private JRFillField field_tdp_tanggal = null;
    private JRFillField field_lokasi_tanggal = null;
    private JRFillField field_luas_tanah = null;
    private JRFillField field_nilai_omset2 = null;
    private JRFillField field_nilai_omset3 = null;
    private JRFillField field_nama_pimpinan = null;
    private JRFillField field_kapasitas_terpasang = null;
    private JRFillField field_eksport = null;
    private JRFillField field_nilai_omset1 = null;
    private JRFillField field_realisasi_produksi = null;
    private JRFillField field_modal_tetap = null;
    private JRFillField field_gudang_nomor = null;
    private JRFillField field_lokasi_nomor = null;
    private JRFillField field_luas_gedung = null;
    private JRFillField field_siup_tanggal = null;
    private JRFillField field_tahun_kegiatan = null;
    private JRFillField field_tahun_omset2 = null;
    private JRFillField field_jenis = null;
    private JRFillField field_jml_tka_p = null;
    private JRFillField field_tahun_omset1 = null;
    private JRFillField field_tahun_omset3 = null;
    private JRFillField field_jml_tka_l = null;
    private JRFillField field_npwp = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_ho_nomor = (JRFillField)fm.get("ho_nomor");
        field_nama_perusahaan = (JRFillField)fm.get("nama_perusahaan");
        field_imb_nomor = (JRFillField)fm.get("imb_nomor");
        field_modal_kerja = (JRFillField)fm.get("modal_kerja");
        field_kota = (JRFillField)fm.get("kota");
        field_gudang_tanggal = (JRFillField)fm.get("gudang_tanggal");
        field_dok_amdal = (JRFillField)fm.get("dok_amdal");
        field_nilai_eksport = (JRFillField)fm.get("nilai_eksport");
        field_jenis_produksi = (JRFillField)fm.get("jenis_produksi");
        field_jml_tki_p = (JRFillField)fm.get("jml_tki_p");
        field_jml_tki_l = (JRFillField)fm.get("jml_tki_l");
        field_imb_tanggal = (JRFillField)fm.get("imb_tanggal");
        field_alamat_jalan = (JRFillField)fm.get("alamat_jalan");
        field_nama = (JRFillField)fm.get("nama");
        field_tdp_nomor = (JRFillField)fm.get("tdp_nomor");
        field_telp = (JRFillField)fm.get("telp");
        field_siup_nomor = (JRFillField)fm.get("siup_nomor");
        field_ho_tanggal = (JRFillField)fm.get("ho_tanggal");
        field_produk = (JRFillField)fm.get("produk");
        field_fax = (JRFillField)fm.get("fax");
        field_tdp_tanggal = (JRFillField)fm.get("tdp_tanggal");
        field_lokasi_tanggal = (JRFillField)fm.get("lokasi_tanggal");
        field_luas_tanah = (JRFillField)fm.get("luas_tanah");
        field_nilai_omset2 = (JRFillField)fm.get("nilai_omset2");
        field_nilai_omset3 = (JRFillField)fm.get("nilai_omset3");
        field_nama_pimpinan = (JRFillField)fm.get("nama_pimpinan");
        field_kapasitas_terpasang = (JRFillField)fm.get("kapasitas_terpasang");
        field_eksport = (JRFillField)fm.get("eksport");
        field_nilai_omset1 = (JRFillField)fm.get("nilai_omset1");
        field_realisasi_produksi = (JRFillField)fm.get("realisasi_produksi");
        field_modal_tetap = (JRFillField)fm.get("modal_tetap");
        field_gudang_nomor = (JRFillField)fm.get("gudang_nomor");
        field_lokasi_nomor = (JRFillField)fm.get("lokasi_nomor");
        field_luas_gedung = (JRFillField)fm.get("luas_gedung");
        field_siup_tanggal = (JRFillField)fm.get("siup_tanggal");
        field_tahun_kegiatan = (JRFillField)fm.get("tahun_kegiatan");
        field_tahun_omset2 = (JRFillField)fm.get("tahun_omset2");
        field_jenis = (JRFillField)fm.get("jenis");
        field_jml_tka_p = (JRFillField)fm.get("jml_tka_p");
        field_tahun_omset1 = (JRFillField)fm.get("tahun_omset1");
        field_tahun_omset3 = (JRFillField)fm.get("tahun_omset3");
        field_jml_tka_l = (JRFillField)fm.get("jml_tka_l");
        field_npwp = (JRFillField)fm.get("npwp");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama_perusahaan.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama_pimpinan.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)field_alamat_jalan.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)field_kota.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)field_telp.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_fax.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_luas_tanah.getValue()));//$JR_EXPR_ID=15$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama_perusahaan.getOldValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama_pimpinan.getOldValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)field_alamat_jalan.getOldValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama.getOldValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)field_kota.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)field_telp.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_fax.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_luas_tanah.getOldValue()));//$JR_EXPR_ID=15$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama_perusahaan.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama_pimpinan.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)field_alamat_jalan.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nama.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)field_kota.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)field_telp.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_fax.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_luas_tanah.getValue()));//$JR_EXPR_ID=15$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
