/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainApps.java
 *
 * Created on Sep 25, 2011, 6:36:34 PM
 */
package com.x3.dishub.ui;

import java.io.FileInputStream;
import java.util.Properties;
import javax.swing.JOptionPane;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author Hendro Steven
 */
public class MainApps extends javax.swing.JFrame {

    public static ClassPathXmlApplicationContext appContext;
    private Properties prop = new Properties();

    private void readProperties() {
        try {
            prop.load(new FileInputStream("conf.properties"));
            System.setProperty("url", prop.getProperty("url"));
            System.setProperty("user", prop.getProperty("user"));
            System.setProperty("pwd", prop.getProperty("pwd"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /** Creates new form MainApps */
    public MainApps() {
        readProperties();
        appContext = new ClassPathXmlApplicationContext(new String[]{"classpath:/com/x3/dishub/dao/applicationContext.xml"});
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(51, 102, 255));
        this.setLocationRelativeTo(null);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnKendaraan = new javax.swing.JButton();
        btnPemilik = new javax.swing.JButton();
        btnPerusahaan = new javax.swing.JButton();
        btnIjinUsaha = new javax.swing.JButton();
        btnSuratPersetujuan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnIjinTrayek = new javax.swing.JButton();
        btnSk = new javax.swing.JButton();
        btnKartuPengawasan = new javax.swing.JButton();
        btnKartuJamPerjalanan = new javax.swing.JButton();
        btnIjinInsidentil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mnu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuMaster = new javax.swing.JMenu();
        mnuMerkKendaraan = new javax.swing.JMenuItem();
        mnuJenisKendaraan = new javax.swing.JMenuItem();
        mnuBahanBakar = new javax.swing.JMenuItem();
        mnuKabKota = new javax.swing.JMenuItem();
        mnuProvinsi = new javax.swing.JMenuItem();
        mnuBadanUsaha = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuDatabase = new javax.swing.JMenu();
        mnuKendaraan = new javax.swing.JMenuItem();
        mnuPemilik = new javax.swing.JMenuItem();
        mnuPerusahaan = new javax.swing.JMenuItem();
        mnuMasterTrayek = new javax.swing.JMenuItem();
        mnuPerijinan = new javax.swing.JMenu();
        mnuIjinUsaha = new javax.swing.JMenu();
        mnuAktOrg = new javax.swing.JMenuItem();
        mnuAktBrg = new javax.swing.JMenuItem();
        mnuSuratPersetujuan = new javax.swing.JMenu();
        mnuSpio = new javax.swing.JMenuItem();
        mnuSpit = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuIjinTrayek = new javax.swing.JMenu();
        mnuTrayek = new javax.swing.JMenuItem();
        mnuOperasi = new javax.swing.JMenuItem();
        mnuSKPelaksana = new javax.swing.JMenu();
        mnuSkTrayek = new javax.swing.JMenuItem();
        mnuSkOperasi = new javax.swing.JMenuItem();
        mnuKartuPengawasan = new javax.swing.JMenu();
        mnuPengawasanUmum = new javax.swing.JMenuItem();
        mnuPengawasanTaksi = new javax.swing.JMenuItem();
        mnuKartuJamPerjalanan = new javax.swing.JMenuItem();
        mnuIjinInsidentil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Data Kendaraan - Dishub Kota Surakarta");

        jToolBar1.setBackground(new java.awt.Color(0, 0, 204));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btnKendaraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/kendaraan.png"))); // NOI18N
        btnKendaraan.setToolTipText("Data Kendaraan");
        btnKendaraan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKendaraan.setFocusable(false);
        btnKendaraan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKendaraan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKendaraanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKendaraan);

        btnPemilik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/pemilik.png"))); // NOI18N
        btnPemilik.setToolTipText("Data Pemilik");
        btnPemilik.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPemilik.setFocusable(false);
        btnPemilik.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPemilik.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemilikActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPemilik);

        btnPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/perusahaan.png"))); // NOI18N
        btnPerusahaan.setToolTipText("Data Perusahaan");
        btnPerusahaan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerusahaan.setFocusable(false);
        btnPerusahaan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPerusahaan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerusahaanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPerusahaan);

        btnIjinUsaha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/ijin_usaha.png"))); // NOI18N
        btnIjinUsaha.setToolTipText("Ijin Usaha");
        btnIjinUsaha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIjinUsaha.setFocusable(false);
        btnIjinUsaha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIjinUsaha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIjinUsaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIjinUsahaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIjinUsaha);

        btnSuratPersetujuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/surat_persetujuan.png"))); // NOI18N
        btnSuratPersetujuan.setToolTipText("Surat Persetujuan");
        btnSuratPersetujuan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuratPersetujuan.setFocusable(false);
        btnSuratPersetujuan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuratPersetujuan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSuratPersetujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratPersetujuanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSuratPersetujuan);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/ijin_insidentil.png"))); // NOI18N
        jButton1.setToolTipText("Surat Keterangan");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btnIjinTrayek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/ijin_trayek.png"))); // NOI18N
        btnIjinTrayek.setToolTipText("Ijin Trayek");
        btnIjinTrayek.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIjinTrayek.setFocusable(false);
        btnIjinTrayek.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIjinTrayek.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIjinTrayek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIjinTrayekActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIjinTrayek);

        btnSk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/sk_pelaksanaan.png"))); // NOI18N
        btnSk.setToolTipText("Sk Pelaksanaan");
        btnSk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSk.setFocusable(false);
        btnSk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSk);

        btnKartuPengawasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/kartu_pengawasan.png"))); // NOI18N
        btnKartuPengawasan.setToolTipText("Kartu Pengawasan");
        btnKartuPengawasan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKartuPengawasan.setFocusable(false);
        btnKartuPengawasan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKartuPengawasan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKartuPengawasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKartuPengawasanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKartuPengawasan);

        btnKartuJamPerjalanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/kartu_jam_perjalanan.png"))); // NOI18N
        btnKartuJamPerjalanan.setToolTipText("Kartu Jam Perjalanan");
        btnKartuJamPerjalanan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKartuJamPerjalanan.setFocusable(false);
        btnKartuJamPerjalanan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKartuJamPerjalanan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKartuJamPerjalanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKartuJamPerjalananActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKartuJamPerjalanan);

        btnIjinInsidentil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/ijin_insidentil.png"))); // NOI18N
        btnIjinInsidentil.setToolTipText("Ijin Insidentil");
        btnIjinInsidentil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIjinInsidentil.setFocusable(false);
        btnIjinInsidentil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIjinInsidentil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIjinInsidentil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIjinInsidentilActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIjinInsidentil);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/x3/dishub/ui/img/surakarta.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PEMERINTAH KOTA SURAKARTA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("D I N A S   P E R H U B U N G A N ");

        mnuFile.setText("File");

        mnuMaster.setText("Master Data");

        mnuMerkKendaraan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        mnuMerkKendaraan.setText("Merk Kendaraan");
        mnuMerkKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMerkKendaraanActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuMerkKendaraan);

        mnuJenisKendaraan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        mnuJenisKendaraan.setText("Jenis Kendaraan");
        mnuJenisKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJenisKendaraanActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuJenisKendaraan);

        mnuBahanBakar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mnuBahanBakar.setText("Bahan Bakar");
        mnuBahanBakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBahanBakarActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuBahanBakar);

        mnuKabKota.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mnuKabKota.setText("Kabupaten Kota");
        mnuKabKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKabKotaActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuKabKota);

        mnuProvinsi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuProvinsi.setText("Provinsi");
        mnuProvinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProvinsiActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuProvinsi);

        mnuBadanUsaha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuBadanUsaha.setText("Bentuk Badan Usaha");
        mnuBadanUsaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBadanUsahaActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuBadanUsaha);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Kelas Pelayanan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuMaster.add(jMenuItem1);

        mnuFile.add(mnuMaster);
        mnuFile.add(jSeparator1);

        mnuKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        mnu.add(mnuFile);

        mnuDatabase.setText("Database");

        mnuKendaraan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mnuKendaraan.setText("Data Kendaraan");
        mnuKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKendaraanActionPerformed(evt);
            }
        });
        mnuDatabase.add(mnuKendaraan);

        mnuPemilik.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPemilik.setText("Data Pemilik");
        mnuPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPemilikActionPerformed(evt);
            }
        });
        mnuDatabase.add(mnuPemilik);

        mnuPerusahaan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuPerusahaan.setText("Data Perusahaan");
        mnuPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPerusahaanActionPerformed(evt);
            }
        });
        mnuDatabase.add(mnuPerusahaan);

        mnuMasterTrayek.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnuMasterTrayek.setText("Data Trayek");
        mnuMasterTrayek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMasterTrayekActionPerformed(evt);
            }
        });
        mnuDatabase.add(mnuMasterTrayek);

        mnu.add(mnuDatabase);

        mnuPerijinan.setText("Perijinan");

        mnuIjinUsaha.setText("Ijin Usaha");

        mnuAktOrg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuAktOrg.setText("Angkutan Orang");
        mnuAktOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAktOrgActionPerformed(evt);
            }
        });
        mnuIjinUsaha.add(mnuAktOrg);

        mnuAktBrg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuAktBrg.setText("Angkutan Barang");
        mnuAktBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAktBrgActionPerformed(evt);
            }
        });
        mnuIjinUsaha.add(mnuAktBrg);

        mnuPerijinan.add(mnuIjinUsaha);

        mnuSuratPersetujuan.setText("Surat Persetujuan");

        mnuSpio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSpio.setText("SPIO");
        mnuSpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSpioActionPerformed(evt);
            }
        });
        mnuSuratPersetujuan.add(mnuSpio);

        mnuSpit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSpit.setText("SPIT");
        mnuSpit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSpitActionPerformed(evt);
            }
        });
        mnuSuratPersetujuan.add(mnuSpit);

        mnuPerijinan.add(mnuSuratPersetujuan);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Surat Keterangan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuPerijinan.add(jMenuItem2);

        mnuIjinTrayek.setText("Ijin Trayek dan Operasi");

        mnuTrayek.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuTrayek.setText("Ijin Trayek");
        mnuTrayek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrayekActionPerformed(evt);
            }
        });
        mnuIjinTrayek.add(mnuTrayek);

        mnuOperasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuOperasi.setText("Ijin Operasi");
        mnuOperasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOperasiActionPerformed(evt);
            }
        });
        mnuIjinTrayek.add(mnuOperasi);

        mnuPerijinan.add(mnuIjinTrayek);

        mnuSKPelaksana.setText("SK Pelaksanaan");

        mnuSkTrayek.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSkTrayek.setText("Pelaksanaan Ijin Trayek");
        mnuSkTrayek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSkTrayekActionPerformed(evt);
            }
        });
        mnuSKPelaksana.add(mnuSkTrayek);

        mnuSkOperasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSkOperasi.setText("Pelaksanaan Ijin Operasi");
        mnuSkOperasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSkOperasiActionPerformed(evt);
            }
        });
        mnuSKPelaksana.add(mnuSkOperasi);

        mnuPerijinan.add(mnuSKPelaksana);

        mnuKartuPengawasan.setText("Kartu Pengawasan");

        mnuPengawasanUmum.setText("Angkutan dan Bis Umum");
        mnuPengawasanUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPengawasanUmumActionPerformed(evt);
            }
        });
        mnuKartuPengawasan.add(mnuPengawasanUmum);

        mnuPengawasanTaksi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPengawasanTaksi.setText("Taksi");
        mnuPengawasanTaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPengawasanTaksiActionPerformed(evt);
            }
        });
        mnuKartuPengawasan.add(mnuPengawasanTaksi);

        mnuPerijinan.add(mnuKartuPengawasan);

        mnuKartuJamPerjalanan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        mnuKartuJamPerjalanan.setText("Kartu Jam Perjalanan");
        mnuKartuJamPerjalanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKartuJamPerjalananActionPerformed(evt);
            }
        });
        mnuPerijinan.add(mnuKartuJamPerjalanan);

        mnuIjinInsidentil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        mnuIjinInsidentil.setText("Ijin Insidentil");
        mnuIjinInsidentil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIjinInsidentilActionPerformed(evt);
            }
        });
        mnuPerijinan.add(mnuIjinInsidentil);

        mnu.add(mnuPerijinan);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(200, 200, 200))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMerkKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMerkKendaraanActionPerformed
        MerkDialog merkDialog = new MerkDialog(this, false);
        merkDialog.setVisible(true);
    }//GEN-LAST:event_mnuMerkKendaraanActionPerformed

    private void mnuJenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuJenisKendaraanActionPerformed
        JenisDialog jenisDialog = new JenisDialog(this, false);
        jenisDialog.setVisible(true);
    }//GEN-LAST:event_mnuJenisKendaraanActionPerformed

    private void mnuBahanBakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBahanBakarActionPerformed
        BahanBakarDialog bahanBakarDialog = new BahanBakarDialog(this, false);
        bahanBakarDialog.setVisible(true);
    }//GEN-LAST:event_mnuBahanBakarActionPerformed

    private void mnuKabKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKabKotaActionPerformed
        KabKotaDialog kkDialog = new KabKotaDialog(this, false);
        kkDialog.setVisible(true);
    }//GEN-LAST:event_mnuKabKotaActionPerformed

    private void mnuProvinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProvinsiActionPerformed
        ProvinsiDialog provinsiDialog = new ProvinsiDialog(this, false);
        provinsiDialog.setVisible(true);
    }//GEN-LAST:event_mnuProvinsiActionPerformed

    private void mnuBadanUsahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBadanUsahaActionPerformed
        BentukBadanUsahaDialog bbuDialog = new BentukBadanUsahaDialog(this, false);
        bbuDialog.setVisible(true);
    }//GEN-LAST:event_mnuBadanUsahaActionPerformed

    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Keluar", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            appContext.close();
            appContext = null;
            System.exit(0);
        }
    }//GEN-LAST:event_mnuKeluarActionPerformed

    private void mnuKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKendaraanActionPerformed
        KendaraanDialog kendaraanDialog = new KendaraanDialog(this, false);
        kendaraanDialog.setVisible(true);
    }//GEN-LAST:event_mnuKendaraanActionPerformed

    private void btnKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKendaraanActionPerformed
        KendaraanDialog kendaraanDialog = new KendaraanDialog(this, false);
        kendaraanDialog.setVisible(true);
    }//GEN-LAST:event_btnKendaraanActionPerformed

    private void mnuPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPemilikActionPerformed
        PemilikDialog pemilikDialog = new PemilikDialog(this, false);
        pemilikDialog.setVisible(true);
    }//GEN-LAST:event_mnuPemilikActionPerformed

    private void btnPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemilikActionPerformed
        PemilikDialog pemilikDialog = new PemilikDialog(this, false);
        pemilikDialog.setVisible(true);
    }//GEN-LAST:event_btnPemilikActionPerformed

    private void mnuPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPerusahaanActionPerformed
        PerusahaanDialog perusahaanDialog = new PerusahaanDialog(this, false);
        perusahaanDialog.setVisible(true);
    }//GEN-LAST:event_mnuPerusahaanActionPerformed

    private void btnPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerusahaanActionPerformed
        PerusahaanDialog perusahaanDialog = new PerusahaanDialog(this, false);
        perusahaanDialog.setVisible(true);
    }//GEN-LAST:event_btnPerusahaanActionPerformed

    private void mnuMasterTrayekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMasterTrayekActionPerformed
        TrayekDialog trayekDialog = new TrayekDialog(this, false);
        trayekDialog.setVisible(true);
    }//GEN-LAST:event_mnuMasterTrayekActionPerformed

    private void mnuAktOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAktOrgActionPerformed
        IjinUsahaAngkutanOrangDialog ijin = new IjinUsahaAngkutanOrangDialog(this, false);
        ijin.setVisible(true);
    }//GEN-LAST:event_mnuAktOrgActionPerformed

    private void btnIjinUsahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIjinUsahaActionPerformed
        PilihIjinUsahaDialog pilih = new PilihIjinUsahaDialog(this, true);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnIjinUsahaActionPerformed

    private void mnuAktBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAktBrgActionPerformed
        IjinUsahaAngkutanBarangDialog ijin = new IjinUsahaAngkutanBarangDialog(this, false);
        ijin.setVisible(true);
    }//GEN-LAST:event_mnuAktBrgActionPerformed

    private void mnuSpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSpioActionPerformed
        SpioDialog spio = new SpioDialog(this, false);
        spio.setVisible(true);
    }//GEN-LAST:event_mnuSpioActionPerformed

    private void mnuSpitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSpitActionPerformed
        SpitDialog spit = new SpitDialog(this, false);
        spit.setVisible(true);
    }//GEN-LAST:event_mnuSpitActionPerformed

    private void btnSuratPersetujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratPersetujuanActionPerformed
        PilihSuratPersetujuanDialog dialog = new PilihSuratPersetujuanDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSuratPersetujuanActionPerformed

    private void mnuTrayekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrayekActionPerformed
        IjinTrayekDialog trayek = new IjinTrayekDialog(this, false);
        trayek.setVisible(true);
    }//GEN-LAST:event_mnuTrayekActionPerformed

    private void mnuOperasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOperasiActionPerformed
        IjinOperasiDialog operasi = new IjinOperasiDialog(this, false);
        operasi.setVisible(true);
    }//GEN-LAST:event_mnuOperasiActionPerformed

    private void btnIjinTrayekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIjinTrayekActionPerformed
        PilihIjinTrayekDialog pilih = new PilihIjinTrayekDialog(this, true);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnIjinTrayekActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        KelasPelayananDialog kelas = new KelasPelayananDialog(this, false);
        kelas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnSkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkActionPerformed
        PilihSKPelaksanaanDialog pilih = new PilihSKPelaksanaanDialog(this, true);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnSkActionPerformed

    private void mnuSkTrayekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSkTrayekActionPerformed
        SKPelaksanaanIjinTrayekDialog sk = new SKPelaksanaanIjinTrayekDialog(this, false);
        sk.setVisible(true);
    }//GEN-LAST:event_mnuSkTrayekActionPerformed

    private void mnuSkOperasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSkOperasiActionPerformed
        SKPelaksanaanIjinOperasiDialog sk = new SKPelaksanaanIjinOperasiDialog(this, false);
        sk.setVisible(true);
    }//GEN-LAST:event_mnuSkOperasiActionPerformed

    private void btnKartuPengawasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKartuPengawasanActionPerformed
        PilihKartuPengawasanDialog pilih = new PilihKartuPengawasanDialog(this, true);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnKartuPengawasanActionPerformed

    private void mnuPengawasanUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPengawasanUmumActionPerformed
        KartuPengawasanOtobisUmumDialog kartu = new KartuPengawasanOtobisUmumDialog(this, false);
        kartu.setVisible(true);
    }//GEN-LAST:event_mnuPengawasanUmumActionPerformed

    private void mnuPengawasanTaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPengawasanTaksiActionPerformed
        KartuPengawasanTaksiDialog kartu = new KartuPengawasanTaksiDialog(this, false);
        kartu.setVisible(true);
    }//GEN-LAST:event_mnuPengawasanTaksiActionPerformed

    private void btnKartuJamPerjalananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKartuJamPerjalananActionPerformed
        KartuJamPerjalananDialog kartu = new KartuJamPerjalananDialog(this, false);
        kartu.setVisible(true);
    }//GEN-LAST:event_btnKartuJamPerjalananActionPerformed

    private void mnuKartuJamPerjalananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKartuJamPerjalananActionPerformed
        KartuJamPerjalananDialog kartu = new KartuJamPerjalananDialog(this, false);
        kartu.setVisible(true);
    }//GEN-LAST:event_mnuKartuJamPerjalananActionPerformed

    private void btnIjinInsidentilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIjinInsidentilActionPerformed
        IjinInsidentilDialog ijin = new IjinInsidentilDialog(this, false);
        ijin.setVisible(true);
    }//GEN-LAST:event_btnIjinInsidentilActionPerformed

    private void mnuIjinInsidentilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIjinInsidentilActionPerformed
        IjinInsidentilDialog ijin = new IjinInsidentilDialog(this, false);
        ijin.setVisible(true);
    }//GEN-LAST:event_mnuIjinInsidentilActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SuratKeteranganDialog surat = new SuratKeteranganDialog(this, false);
        surat.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SuratKeteranganDialog surat = new SuratKeteranganDialog(this, false);
        surat.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainApps().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIjinInsidentil;
    private javax.swing.JButton btnIjinTrayek;
    private javax.swing.JButton btnIjinUsaha;
    private javax.swing.JButton btnKartuJamPerjalanan;
    private javax.swing.JButton btnKartuPengawasan;
    private javax.swing.JButton btnKendaraan;
    private javax.swing.JButton btnPemilik;
    private javax.swing.JButton btnPerusahaan;
    private javax.swing.JButton btnSk;
    private javax.swing.JButton btnSuratPersetujuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar mnu;
    private javax.swing.JMenuItem mnuAktBrg;
    private javax.swing.JMenuItem mnuAktOrg;
    private javax.swing.JMenuItem mnuBadanUsaha;
    private javax.swing.JMenuItem mnuBahanBakar;
    private javax.swing.JMenu mnuDatabase;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuIjinInsidentil;
    private javax.swing.JMenu mnuIjinTrayek;
    private javax.swing.JMenu mnuIjinUsaha;
    private javax.swing.JMenuItem mnuJenisKendaraan;
    private javax.swing.JMenuItem mnuKabKota;
    private javax.swing.JMenuItem mnuKartuJamPerjalanan;
    private javax.swing.JMenu mnuKartuPengawasan;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenuItem mnuKendaraan;
    private javax.swing.JMenu mnuMaster;
    private javax.swing.JMenuItem mnuMasterTrayek;
    private javax.swing.JMenuItem mnuMerkKendaraan;
    private javax.swing.JMenuItem mnuOperasi;
    private javax.swing.JMenuItem mnuPemilik;
    private javax.swing.JMenuItem mnuPengawasanTaksi;
    private javax.swing.JMenuItem mnuPengawasanUmum;
    private javax.swing.JMenu mnuPerijinan;
    private javax.swing.JMenuItem mnuPerusahaan;
    private javax.swing.JMenuItem mnuProvinsi;
    private javax.swing.JMenu mnuSKPelaksana;
    private javax.swing.JMenuItem mnuSkOperasi;
    private javax.swing.JMenuItem mnuSkTrayek;
    private javax.swing.JMenuItem mnuSpio;
    private javax.swing.JMenuItem mnuSpit;
    private javax.swing.JMenu mnuSuratPersetujuan;
    private javax.swing.JMenuItem mnuTrayek;
    // End of variables declaration//GEN-END:variables
}
